trigger:
  - main
  - development

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'

stages:
  - stage: build
    displayName: "Build Application"
    jobs:
      - job: Build
        displayName: "Build Job"

        steps:
          - checkout: self
            fetchDepth: 0

          - script: chmod +x gradlew
            displayName: 'Make gradlew executable'

          # Ensure correct JDK is available
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '$(javaVersion)'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          
          # Establish SonarCloud connection and run analysis
          - task: SonarCloudPrepare@3
            inputs:
              SonarQube: 'SonarConnection'
              organization: 'x00219439'
              scannerMode: 'other'
              extraProperties: |
                # Additional properties that will be passed to the scanner,
                # Put one key=value per line, example:
                # sonar.exclusions=**/*.bin
                sonar.projectKey=X00219439_X00219439_CA2
                sonar.projectName=X00219439_CA2

          # Run Gradle tasks
          - task: Gradle@3
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'clean build test jacocoTestReport sonar'

          # Publish code coverage results to Azure
          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml'
              pathToSources: '$(System.DefaultWorkingDirectory)/app/src/main/java/'

          # Publish SonarCloud results
          - task: SonarCloudPublish@3
            inputs:
              pollingTimeoutSec: '300'

          # Copy JAR files into the artifact staging directory for use in later stages
          - task: CopyFiles@2
            displayName: 'Copy jar files'
            inputs:
              contents: '**/build/libs/*SNAPSHOT.jar'
              targetFolder: '$(build.artifactStagingDirectory)'

          # Debugging
          - script: |
              echo "Listing files in $(build.artifactStagingDirectory):"
              ls -R $(build.artifactStagingDirectory)
            displayName: "Verify Files Copied to Artifact Staging Directory"

          # Publish other build artifacts into the artifact staging directory for use in later stages
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: deploy
    jobs:
      - deployment: deploy
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:

            # Ensure correct JDK is available
              - task: JavaToolInstaller@0
                inputs:
                  versionSpec: '$(javaVersion)'
                  jdkArchitectureOption: 'x64'
                  jdkSourceOption: 'PreInstalled'

              # Download the JAR file from the build stage
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.ArtifactsDirectory)'

              # Find the JAR file and run it
              - script: |
                  JAR_FILE=$(find $(System.ArtifactsDirectory) -name *SNAPSHOT.jar)
                  if [ -z "$JAR_FILE" ]; then
                    echo "No JAR file found"
                    exit 1
                  fi
                  echo "Found JAR file: $JAR_FILE"
                  java -jar $JAR_FILE &