trigger:
  - main
  - development

stages:
  - stage: build
    displayName: "Build Application"
    jobs:
      - job: Build
        displayName: "Build Job"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: chmod +x gradlew
            displayName: 'Make gradlew executable'

          - task: SonarCloudPrepare@3
            inputs:
              SonarCloud: 'SonarConnection'
              organization: 'X00219439'
              scannerMode: 'other'
              extraProperties: |
                sonar.projectKey=x00219439
                sonar.projectName=X00219439

          - task: Gradle@3
            inputs:
              workingDirectory: ''
              gradleWrapperFile: 'gradlew'
              gradleOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'clean build test jacocoTestReport sonar'

          - task: PublishCodeCoverageResults@2
            inputs:
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml'
              pathToSources: '$(System.DefaultWorkingDirectory)/app/src/main/java/'

          - task: SonarCloudPublish@3
            inputs:
              pollingTimeoutSec: '300'